language: node_js

node_js: 
  - stable

services:
 - mongodb

install:
  - npm install

script:
 - npm test

before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'